inherit_mode:
  merge:
    - Exclude
require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.0.1
  Exclude:
  - "vendor/**/*"
  - "**/tmp/**/*"
  - "**/db/**/*"
  - "**/bin/**/*"
  - "**/config/environments/**/*"
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  NewCops: enable

Style/Encoding:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - class_methods
Layout/LineLength:
  Description: Limit lines to 120 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 120
  AllowURI: true
  URISchemes:
  - http
  - https
Layout/EmptyLinesAroundClassBody:
  Description: Keeps track of empty lines around class bodies.
  Enabled: true
  EnforcedStyle: empty_lines
  SupportedStyles:
  - empty_lines
  - no_empty_lines
Style/RegexpLiteral:
  Description: Use %r for regular expressions matching more than `MaxSlashes` '/'
    characters. Use %r only for regular expressions matching more than `MaxSlashes`
    '/' character.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#percent-r
  Enabled: false
Metrics/BlockLength:
  Max: 315
  Enabled: true
  Exclude:
    - spec/**/*
Rails/DynamicFindBy:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Lint/MissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - "spec/integration/*.rb"
Security/YAMLLoad:
  Exclude:
    - "spec/**/*.rb"
Naming/MethodParameterName:
  MinNameLength: 2
  AllowedNames:
    - "_"
Naming/MemoizedInstanceVariableName:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 10
RSpec/MultipleExpectations:
  Max: 12
RSpec/MessageSpies:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/VariableName:
  Enabled: true
  Exclude:
    - "spec/integration/*.rb"
