default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] || '127.0.0.1' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>

development:
  <<: *default
  database: Smartflix_development

test:
  <<: *default
  database: Smartflix_test

production:
  <<: *default
  database: Smartflix_production
  username: Smartflix
  password: <%= ENV['SMARTFLIX_DATABASE_PASSWORD'] %>
