default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  username: postgres
  password:

development:
  <<: *default
  database: Smartflix_development

test:
  <<: *default
  database: Smartflix_test

production:
  <<: *default
  database: Smartflix_production
  username: Smartflix
