---
:concurrency: 3
:queues:
  - default
  - movies
:schedule:
  update_movies_in_db:
    cron: '0 7 * * *'
    class: UpdateMoviesWorker
  delete_outdated_movies:
    cron: '0 8 * * *'
    class: RemoveOutdatedMoviesWorker